In [2]:
import pandas as pd

In [3]:
info = {
    "Name" : ["Abc", "Xyz"],
    "cgpa" : [9.5, 7.5]
}
df = pd.DataFrame(info)
df

  Name  cgpa
0  Abc   9.5
1  Xyz   7.5

In [5]:
s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(type(s))

#index based access
print(s[2])
print(s[0])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
3
1

In [8]:
#labels
s = pd.Series([23, 24, 25], index = ["Adam", "Steve", "Bob"])
print(s)
print(s["Steve"])
print(s[1])

Adam     23
Steve    24
Bob      25
dtype: int64
24
24

C:\Users\Anuja Kharat\AppData\Local\Temp\ipykernel_29672\4127695280.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1])

In [5]:
#Series are homogeneous
s1 = pd.Series([1, 2, 3, "abc"])
print(s1)

#Series perform vectorized operation
s01 = pd.Series([1, 2, 3, 4])
s2 = pd.Series([10, 20, 30, 40])
print(s01 + s2)

#Series have mutable values but immutable size
print(s1[0])
s01[0] = 100
print(s01)
changed_s01 = s01.drop(0)
print(s01)
print(changed_s01)

0      1
1      2
2      3
3    abc
dtype: object
0    11
1    22
2    33
3    44
dtype: int64
1
0    100
1      2
2      3
3      4
dtype: int64
0    100
1      2
2      3
3      4
dtype: int64
1    2
2    3
3    4
dtype: int64

In [11]:
#DataFrame
info = {
    "Name" : ["Adam", "Eve", "Bob", "Abc"],
    "Age" : [23,24,25, 20],
    "GPA" : [9.2, 8.7, 8.8, 7.03]
}
df = pd.DataFrame(info)
# print(df, type(df))
# df
#index and columns
# print(df.index, df.columns)

RangeIndex(start=0, stop=4, step=1) Index(['Name', 'Age', 'GPA'], dtype='object')

In [12]:
#list of lists
df = pd.DataFrame([["Adam", 23], ["steve", 28], ["Jobs", 24]], columns = ["Name", "Age"])
df

    Name  Age
0   Adam   23
1  steve   28
2   Jobs   24

In [13]:
#Creating DataFrames using Numpy Arrays
import numpy as np

np_arr = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(np_arr, columns = ['A', 'B', 'C'])
df

   A  B  C
0  1  2  3
1  4  5  6

In [14]:
#loading csv data
df = pd.read_csv("employee_data.csv")
print(df, type(df))
#loading json data
df1 = pd.read_json("emp.json")
print(df1, type(df1))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>
   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [31]:
#DataFrame methods
# df.head()
# df.head(2)
# df.tail()
# df.tail(3)
# df.sample(7)
# df.info()
# df.describe()
# df.shape
# df.columns
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [24]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [33]:
df = pd.read_csv("air.csv")
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [37]:
#selecting columns
# df["city"]
df[["city", "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [41]:
#selecting rows - loc, iloc
# df.loc[2]
# df.loc[1500: 1520] #index inclusive
# df.iloc[100]
df.iloc[17980 : 18000] #index exclusive

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17980,2025-11-18 22:25:17.554219,CH,Zurich,47.377,8.542,1.511,72.372,20.131,7.449,39.990,0.440,72,6.622,40.546,3.055
17981,2025-11-18 23:25:17.554219,CH,Zurich,47.377,8.542,55.861,68.860,42.874,8.432,45.235,0.533,111,19.201,62.779,9.423
17982,2025-11-19 00:25:17.554219,CH,Zurich,47.377,8.542,25.716,64.885,33.289,4.439,48.826,1.299,83,18.961,82.495,2.956
17983,2025-11-19 01:25:17.554219,CH,Zurich,47.377,8.542,21.900,84.621,28.605,8.958,53.178,0.621,84,35.020,71.804,8.901
17984,2025-11-19 02:25:17.554219,CH,Zurich,47.377,8.542,15.161,70.873,35.721,8.374,46.769,0.729,89,10.711,45.901,2.259
17985,2025-11-19 03:25:17.554219,CH,Zurich,47.377,8.542,63.413,63.292,29.654,8.252,47.796,0.564,126,20.346,28.876,7.758
17986,2025-11-19 04:25:17.554219,CH,Zurich,47.377,8.542,19.122,24.852,9.014,4.059,77.801,0.890,38,14.021,53.164,1.327
17987,2025-11-19 05:25:17.554219,CH,Zurich,47.377,8.542,34.718,32.183,47.600,7.416,58.935,0.992,118,16.741,25.172,6.199
17988,2025-11-19 06:25:17.554219,CH,Zurich,47.377,8.542,61.305,97.044,23.317,6.793,57.102,1.022,122,13.982,30.822,6.769
17989,2025-11-19 07:25:17.554219,CH,Zurich,47.377,8.542,28.171,93.577,32.823,0.654,71.688,1.133,93,10.150,75.423,7.357
17990,2025-11-19 08:25:17.554219,CH,Zurich,47.377,8.542,29.621,27.051,13.218,9.936,49.502,0.678,59,32.144,67.180,6.809
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17992,2025-11-19 10:25:17.554219,CH,Zurich,47.377,8.542,44.086,87.359,36.588,4.897,50.972,1.191,91,14.728,70.076,9.869
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17994,2025-11-19 12:25:17.554219,CH,Zurich,47.377,8.542,42.982,54.692,37.756,7.528,55.321,0.929,94,35.439,77.027,0.682
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [48]:
#select rows and columns
# df.loc[29, "temperature"]
# df.loc[25:30, ["city", "aqi", "temperature"]]

df.columns
# df.iloc[200, 12]
# df.iloc[23 : 31, 1:4]

   country      city  latitude
23      US  New York    40.713
24      US  New York    40.713
25      US  New York    40.713
26      US  New York    40.713
27      US  New York    40.713
28      US  New York    40.713
29      US  New York    40.713
30      US  New York    40.713

In [50]:
#Accessing individual elements
df.at[0, "city"]
df.iat[0, 8]

np.float64(6.539)

In [53]:
#copy vs view -> while changing any data, make it a copy. Otherwise original data can change
cities = df['city'].copy()
cities[0] = "Mumbai"
df['city']
# cities

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object